version: '2'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: zallpyadm
      POSTGRES_PASSWORD: zallpy2019
      POSTGRES_DB: zallpy_project_management
    ports:
      - '5432:5432'
  backend:
    build:
      context: .
      dockerfile: zallpy-project-manager-backend/Dockerfile
    image: backend
    depends_on:
      - postgres
    ports:
      - '3333:3333'
    command: ['./wait-for-it.sh', 'postgres:5432', '--', 'python', 'app.py']
  frontend:
    build:
      context: .
      dockerfile: zallpy-project-manager-frontend/Dockerfile
    image: frontend
    ports:
      - '80'
  migration:
    image: backend:latest
    command: ['./wait-for-it.sh', 'postgres:5432', '--', 'yarn', 'migrate-seed']
    links:
      - postgres
    depends_on:
      - postgres
